### ISSUE TITLE
Remotes that use ssh instead of https not working.

### ISSUE THREAD

**Issue by VolodymyrPliuta** [MichaelDimmitt/gh_reveal#7]
Remotes that use SSH do not work.
Example: `git@github.com:GoogleScholarship/React-navmenu.git`

**Comment by MichaelDimmitt** [comment]
Nice find @VolodymyrPliuta,

What a whirlwind getting the command to work for https and git instead of just https.
Here is the resultant command and I have input xdg-open since I know you are on linux.

```
echo "$(git remote -v | grep fetch | grep -o 'github.*' |  awk '{print $1}' | sed 's/.git$//' | cut -c 12- )" | xargs -I {} xdg-open https://www.github.com/{}
```
